//! Parser for the hosts file generated by upstream WPT tooling.

use std::fmt;
use std::fs;
use std::net::IpAddr;
use std::path::{Path, PathBuf};

use raikiri_net::HostResolverOverrides;

/// Hostname mappings parsed from a WPT hosts file.
#[derive(Debug)]
pub struct WptHostResolver {
    overrides: HostResolverOverrides,
}

impl WptHostResolver {
    /// Parses `path`, rejecting malformed lines and conflicting aliases.
    pub fn from_hosts_file(path: impl AsRef<Path>) -> Result<Self, WptHostResolverError> {
        let path = path.as_ref();
        let source = fs::read_to_string(path).map_err(|source| WptHostResolverError {
            path: path.to_path_buf(),
            line: None,
            message: source.to_string(),
        })?;
        let mut overrides = HostResolverOverrides::new();

        for (index, raw_line) in source.lines().enumerate() {
            let line_number = index + 1;
            let line = raw_line.split_once('#').map_or(raw_line, |(line, _)| line);
            let mut fields = line.split_whitespace();
            let Some(address_text) = fields.next() else {
                continue;
            };
            let address = address_text.parse::<IpAddr>().map_err(|error| {
                WptHostResolverError::at_line(
                    path,
                    line_number,
                    format!("invalid IP address {address_text:?}: {error}"),
                )
            })?;
            let aliases = fields.collect::<Vec<_>>();
            if aliases.is_empty() {
                return Err(WptHostResolverError::at_line(
                    path,
                    line_number,
                    "expected at least one hostname after the address",
                ));
            }
            for alias in aliases {
                if alias.is_empty() {
                    return Err(WptHostResolverError::at_line(
                        path,
                        line_number,
                        "hostname must not be empty",
                    ));
                }
                if let Some(previous) = overrides.get(alias)
                    && previous != address
                {
                    return Err(WptHostResolverError::at_line(
                        path,
                        line_number,
                        format!("hostname {alias:?} maps to both {previous} and {address}"),
                    ));
                }
                overrides.insert(alias, address);
            }
        }

        Ok(Self { overrides })
    }

    /// Converts the parsed WPT aliases into generic HTTP resolver overrides.
    pub fn into_overrides(self) -> HostResolverOverrides {
        self.overrides
    }
}

/// Error produced while reading or parsing a WPT hosts file.
#[derive(Debug)]
pub struct WptHostResolverError {
    path: PathBuf,
    line: Option<usize>,
    message: String,
}

impl WptHostResolverError {
    fn at_line(path: &Path, line: usize, message: impl Into<String>) -> Self {
        Self {
            path: path.to_path_buf(),
            line: Some(line),
            message: message.into(),
        }
    }
}

impl fmt::Display for WptHostResolverError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self.line {
            Some(line) => write!(f, "{}:{line}: {}", self.path.display(), self.message),
            None => write!(f, "{}: {}", self.path.display(), self.message),
        }
    }
}

impl std::error::Error for WptHostResolverError {}

#[cfg(test)]
mod tests;
