//! Fragmentation primitives shared by the Taffy layout seam and paint-facing layout state.
//!
//! A multicolumn container is a formatting-context boundary.  These small
//! value types deliberately do not depend on Taffy's arena or on the cascade:
//! the strategy resolves computed values before constructing a context, then
//! recursively lays out children against that context.

use raikiri_style::property::ColumnFillValue;

/// Used multicolumn settings carried from computed style into the Taffy tree.
#[derive(Clone, Copy, Debug, PartialEq)]
pub(crate) struct MulticolStyle {
    /// Explicit `column-count`, or `None` for `auto`.
    pub(crate) count: Option<usize>,
    /// Explicit positive `column-width`, or `None` for `auto`.
    pub(crate) width: Option<f32>,
    /// `column-fill` controls balancing for auto-height columns.
    pub(crate) column_fill: ColumnFillValue,
    /// Used `column-gap` in CSS px when the authored value is absolute/normal.
    pub(crate) gap: f32,
    /// Authored percentage gap, resolved against the container inline size.
    pub(crate) gap_percent: Option<f32>,
    /// Whether the computed container height is definite rather than an
    /// auto-height generated by the foundational text projection.
    pub(crate) height_definite: bool,
    /// Whether this tranche is in the supported horizontal writing mode.
    pub(crate) horizontal: bool,
    /// Minimum line boxes retained before a line break.
    pub(crate) orphans: usize,
    /// Minimum line boxes retained after a line break.
    pub(crate) widows: usize,
}

/// A local fragmentainer context passed down the nested layout stack.
#[derive(Clone, Copy, Debug, PartialEq)]
pub(crate) struct FragmentationContext {
    /// Inline size available to the current multicol container.
    pub(crate) available_width: f32,
    /// Block size available to the current fragmentainer, when definite.
    pub(crate) available_height: Option<f32>,
    /// Column filling mode used by the current multicol container.
    pub(crate) column_fill: ColumnFillValue,
    /// Used inline size of each column.
    pub(crate) column_width: f32,
    /// Used number of columns.
    pub(crate) column_count: usize,
    /// Used gap between columns.
    pub(crate) column_gap: f32,
    /// Current column in the parent context.
    pub(crate) column_index: usize,
    /// Physical origin supplied by the parent fragment.
    pub(crate) origin_x: f32,
    /// Physical origin supplied by the parent fragment.
    pub(crate) origin_y: f32,
    /// Minimum line boxes retained before a line break.
    pub(crate) orphans: usize,
    /// Minimum line boxes retained after a line break.
    pub(crate) widows: usize,
}

impl FragmentationContext {
    /// Resolve a context from a container width and the computed multicol settings.
    pub(crate) fn resolve(
        available_width: f32,
        available_height: Option<f32>,
        style: MulticolStyle,
    ) -> Option<Self> {
        if !available_width.is_finite() || available_width <= 0.0 {
            return None;
        }
        let gap = if let Some(percent) = style.gap_percent {
            (available_width * percent / 100.0).max(0.0)
        } else if style.gap.is_finite() {
            style.gap.max(0.0)
        } else {
            0.0
        };
        let count = style.count.unwrap_or_else(|| {
            let width = style.width.unwrap_or(available_width).max(1.0);
            (((available_width + gap) / (width + gap)).floor() as usize).max(1)
        });
        let count = count.max(1);
        let usable = (available_width - gap * count.saturating_sub(1) as f32).max(0.0);
        let column_width = usable / count as f32;
        (column_width.is_finite() && column_width > 0.0).then_some(Self {
            available_width,
            available_height,
            column_fill: style.column_fill,
            column_width,
            column_count: count,
            column_gap: gap,
            column_index: 0,
            origin_x: 0.0,
            origin_y: 0.0,
            orphans: style.orphans.max(1),
            widows: style.widows.max(1),
        })
    }

    /// Return a child context translated into one of this container's columns.
    pub(crate) fn in_column(self, column_index: usize, origin_x: f32, origin_y: f32) -> Self {
        Self {
            column_index,
            origin_x,
            origin_y,
            ..self
        }
    }

    /// Physical inline offset of a column in this context.
    pub(crate) fn column_offset_x(self, column_index: usize) -> f32 {
        column_index as f32 * (self.column_width + self.column_gap)
    }
}

/// A resumable point in a fragmented child flow.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) struct BreakToken {
    /// Node whose flow is being resumed.
    pub(crate) node_id: usize,
    /// Child index at which block flow resumes.
    pub(crate) child_index: usize,
    /// Text line index at which inline flow resumes.
    pub(crate) line_index: usize,
}

/// Physical position and size of one fragment in its parent's coordinate space.
#[derive(Clone, Copy, Debug, PartialEq)]
#[doc(hidden)]
pub struct FragmentRect {
    pub x: f32,
    pub y: f32,
    pub width: f32,
    pub height: f32,
}

/// Physical box or text-range fragment emitted by a layout strategy.
#[derive(Clone, Copy, Debug, PartialEq)]
#[doc(hidden)]
pub struct LayoutFragment {
    /// Source DOM node.
    pub node_id: usize,
    /// Parent fragment in the fragment tree, if any.
    pub parent: Option<usize>,
    /// Fragmentainer/column index local to the owning multicol context.
    pub fragmentainer: usize,
    /// Physical position and size relative to the parent fragment's origin.
    pub rect: FragmentRect,
    /// Clip for the owning fragmentainer in the parent fragment's space.
    pub fragmentainer_clip: Option<FragmentRect>,
    /// Zero-based order among fragments of this source node.
    pub fragment_index: usize,
    /// Total number of fragments for this source node.
    pub fragment_count: usize,
    /// Optional text line range. `None` denotes an element/box fragment.
    pub line_start: Option<usize>,
    /// Exclusive text line end when `line_start` is set.
    pub line_end: Option<usize>,
}

impl LayoutFragment {
    /// Resolve this fragment's origin from the current source and fragment parents.
    ///
    /// A root fragment is relative to the source node's layout origin; a
    /// nested fragment is relative to its parent fragment. Both native paint
    /// and page projection use this coordinate seam.
    pub fn paint_origin(
        &self,
        source_parent: (f32, f32),
        source_location: (f32, f32),
        fragment_parent: (f32, f32),
    ) -> (f32, f32) {
        let base = if self.parent.is_some() {
            fragment_parent
        } else {
            (
                source_parent.0 + source_location.0,
                source_parent.1 + source_location.1,
            )
        };
        (base.0 + self.rect.x, base.1 + self.rect.y)
    }
}

// The fixed cap separately bounds retained fragments and additional
// break-flow measurement work before paint construction.
const MAX_LAYOUT_FRAGMENTS: usize = 65_536;

/// Per-layout-pass fragment storage.
#[derive(Clone, Debug)]
pub(crate) struct FragmentTree {
    pub(crate) fragments: Vec<LayoutFragment>,
    /// Break points retained for a later incremental/reflow consumer.
    pub(crate) break_tokens: Vec<BreakToken>,
    /// Separate caps for fragments and estimated break-flow measurement work.
    pub(crate) limit: usize,
    /// Estimated node visits and child scans reserved by break-flow projections.
    pub(crate) break_flow_work_used: usize,
    /// Set when fragment production or break-flow work would exceed `limit`.
    pub(crate) limit_exceeded: bool,
}

impl Default for FragmentTree {
    fn default() -> Self {
        Self {
            fragments: Vec::new(),
            break_tokens: Vec::new(),
            limit: MAX_LAYOUT_FRAGMENTS,
            break_flow_work_used: 0,
            limit_exceeded: false,
        }
    }
}

impl FragmentTree {
    pub(crate) fn clear(&mut self) {
        self.fragments.clear();
        self.break_tokens.clear();
        self.break_flow_work_used = 0;
        self.limit_exceeded = false;
    }

    pub(crate) fn try_push(&mut self, fragment: LayoutFragment) -> Option<usize> {
        if self.fragments.len() >= self.limit {
            self.limit_exceeded = true;
            return None;
        }
        let id = self.fragments.len();
        self.fragments.push(fragment);
        Some(id)
    }

    pub(crate) fn record_break(&mut self, token: BreakToken) {
        self.break_tokens.push(token);
    }

    /// Assign stable source-node order and total counts after layout finishes.
    pub(crate) fn finalize(&mut self) {
        let mut counts = std::collections::HashMap::<usize, usize>::new();
        for fragment in &self.fragments {
            *counts.entry(fragment.node_id).or_default() += 1;
        }
        let mut next = std::collections::HashMap::<usize, usize>::new();
        for fragment in &mut self.fragments {
            let index = next.entry(fragment.node_id).or_default();
            fragment.fragment_index = *index;
            fragment.fragment_count = counts[&fragment.node_id];
            *index += 1;
        }
    }

    /// Attach a nested container root emitted during its recursive layout to
    /// the element fragment that the parent flow placed afterward.
    pub(crate) fn reparent_roots(&mut self, node_id: usize, parent: usize) {
        for fragment in &mut self.fragments {
            if fragment.node_id == node_id && fragment.parent.is_none() {
                fragment.parent = Some(parent);
            }
        }
    }
}

#[cfg(test)]
mod tests;
