//! Fragmentation primitives shared by the Taffy layout seam and paint-facing layout state.
//!
//! A multicolumn container is a formatting-context boundary.  These small
//! value types deliberately do not depend on Taffy's arena or on the cascade:
//! the strategy resolves computed values before constructing a context, then
//! recursively lays out children against that context.

/// Used multicolumn settings carried from computed style into the Taffy tree.
#[derive(Clone, Copy, Debug, PartialEq)]
pub(crate) struct MulticolStyle {
    /// Explicit `column-count`, or `None` for `auto`.
    pub(crate) count: Option<usize>,
    /// Explicit positive `column-width`, or `None` for `auto`.
    pub(crate) width: Option<f32>,
    /// Used `column-gap` in CSS px when the authored value is absolute/normal.
    pub(crate) gap: f32,
    /// Authored percentage gap, resolved against the container inline size.
    pub(crate) gap_percent: Option<f32>,
    /// Whether the computed container height is definite rather than an
    /// auto-height generated by the foundational text projection.
    pub(crate) height_definite: bool,
    /// Whether this tranche is in the supported horizontal writing mode.
    pub(crate) horizontal: bool,
    /// Minimum line boxes retained before a line break.
    pub(crate) orphans: usize,
    /// Minimum line boxes retained after a line break.
    pub(crate) widows: usize,
}

/// A local fragmentainer context passed down the nested layout stack.
#[derive(Clone, Copy, Debug, PartialEq)]
pub(crate) struct FragmentationContext {
    /// Inline size available to the current multicol container.
    pub(crate) available_width: f32,
    /// Block size available to the current fragmentainer, when definite.
    pub(crate) available_height: Option<f32>,
    /// Used inline size of each column.
    pub(crate) column_width: f32,
    /// Used number of columns.
    pub(crate) column_count: usize,
    /// Used gap between columns.
    pub(crate) column_gap: f32,
    /// Current column in the parent context.
    pub(crate) column_index: usize,
    /// Physical origin supplied by the parent fragment.
    pub(crate) origin_x: f32,
    /// Physical origin supplied by the parent fragment.
    pub(crate) origin_y: f32,
    /// Minimum line boxes retained before a line break.
    pub(crate) orphans: usize,
    /// Minimum line boxes retained after a line break.
    pub(crate) widows: usize,
}

impl FragmentationContext {
    /// Resolve a context from a container width and the computed multicol settings.
    pub(crate) fn resolve(
        available_width: f32,
        available_height: Option<f32>,
        style: MulticolStyle,
    ) -> Option<Self> {
        if !available_width.is_finite() || available_width <= 0.0 {
            return None;
        }
        let gap = if let Some(percent) = style.gap_percent {
            (available_width * percent / 100.0).max(0.0)
        } else if style.gap.is_finite() {
            style.gap.max(0.0)
        } else {
            0.0
        };
        let count = style.count.unwrap_or_else(|| {
            let width = style.width.unwrap_or(available_width).max(1.0);
            (((available_width + gap) / (width + gap)).floor() as usize).max(1)
        });
        let count = count.max(1);
        let usable = (available_width - gap * count.saturating_sub(1) as f32).max(0.0);
        let column_width = usable / count as f32;
        (column_width.is_finite() && column_width > 0.0).then_some(Self {
            available_width,
            available_height,
            column_width,
            column_count: count,
            column_gap: gap,
            column_index: 0,
            origin_x: 0.0,
            origin_y: 0.0,
            orphans: style.orphans.max(1),
            widows: style.widows.max(1),
        })
    }

    /// Return a child context translated into one of this container's columns.
    pub(crate) fn in_column(self, column_index: usize, origin_x: f32, origin_y: f32) -> Self {
        Self {
            column_index: column_index.min(self.column_count.saturating_sub(1)),
            origin_x,
            origin_y,
            ..self
        }
    }

    /// Physical inline offset of a column in this context.
    pub(crate) fn column_offset_x(self, column_index: usize) -> f32 {
        column_index as f32 * (self.column_width + self.column_gap)
    }
}

/// A resumable point in a fragmented child flow.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) struct BreakToken {
    /// Node whose flow is being resumed.
    pub(crate) node_id: usize,
    /// Child index at which block flow resumes.
    pub(crate) child_index: usize,
    /// Text line index at which inline flow resumes.
    pub(crate) line_index: usize,
}

/// Physical box or text-range fragment emitted by a layout strategy.
#[derive(Clone, Copy, Debug, PartialEq)]
pub(crate) struct LayoutFragment {
    /// Source DOM node.
    pub(crate) node_id: usize,
    /// Parent fragment in the fragment tree, if any.
    pub(crate) parent: Option<usize>,
    /// Fragmentainer/column index local to the owning multicol context.
    pub(crate) fragmentainer: usize,
    /// Physical position and size relative to the owning layout box.
    pub(crate) x: f32,
    /// Block-axis position relative to the owning layout box.
    pub(crate) y: f32,
    /// Fragment inline size.
    pub(crate) width: f32,
    /// Fragment block size.
    pub(crate) height: f32,
    /// Optional text line range. `None` denotes an element/box fragment.
    pub(crate) line_start: Option<usize>,
    /// Exclusive text line end when `line_start` is set.
    pub(crate) line_end: Option<usize>,
}

/// Per-layout-pass fragment storage.
#[derive(Clone, Debug, Default)]
pub(crate) struct FragmentTree {
    pub(crate) fragments: Vec<LayoutFragment>,
    /// Break points retained for a later incremental/reflow consumer.
    pub(crate) break_tokens: Vec<BreakToken>,
}

impl FragmentTree {
    pub(crate) fn clear(&mut self) {
        self.fragments.clear();
        self.break_tokens.clear();
    }

    pub(crate) fn push(&mut self, fragment: LayoutFragment) -> usize {
        let id = self.fragments.len();
        self.fragments.push(fragment);
        id
    }

    pub(crate) fn record_break(&mut self, token: BreakToken) {
        self.break_tokens.push(token);
    }

    /// Attach a nested container root emitted during its recursive layout to
    /// the element fragment that the parent flow placed afterward.
    pub(crate) fn reparent_roots(&mut self, node_id: usize, parent: usize) {
        for fragment in &mut self.fragments {
            if fragment.node_id == node_id && fragment.parent.is_none() {
                fragment.parent = Some(parent);
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn resolves_count_and_percentage_gap_against_used_width() {
        let context = FragmentationContext::resolve(
            100.0,
            Some(60.0),
            MulticolStyle {
                count: Some(2),
                width: None,
                gap: 0.0,
                gap_percent: Some(10.0),
                height_definite: true,
                horizontal: true,
                orphans: 2,
                widows: 2,
            },
        )
        .expect("positive used width should resolve");
        assert_eq!(context.column_count, 2);
        assert!((context.column_gap - 10.0).abs() < f32::EPSILON);
        assert!((context.column_width - 45.0).abs() < f32::EPSILON);
        let second = context.in_column(1, context.column_offset_x(1), 12.0);
        assert_eq!(second.column_index, 1);
        assert_eq!(second.origin_y, 12.0);
        assert!(
            FragmentationContext::resolve(
                0.0,
                None,
                MulticolStyle {
                    count: None,
                    width: None,
                    gap: 0.0,
                    gap_percent: None,
                    height_definite: false,
                    horizontal: true,
                    orphans: 2,
                    widows: 2,
                },
            )
            .is_none()
        );
        let inferred = FragmentationContext::resolve(
            100.0,
            None,
            MulticolStyle {
                count: None,
                width: Some(30.0),
                gap: 5.0,
                gap_percent: None,
                height_definite: false,
                horizontal: true,
                orphans: 2,
                widows: 2,
            },
        )
        .expect("auto count should derive from width");
        assert_eq!(inferred.column_count, 3);
        let non_finite_gap = FragmentationContext::resolve(
            100.0,
            None,
            MulticolStyle {
                count: Some(1),
                width: None,
                gap: f32::NAN,
                gap_percent: None,
                height_definite: false,
                horizontal: true,
                orphans: 2,
                widows: 2,
            },
        )
        .expect("non-finite gap should fail closed to zero");
        assert_eq!(non_finite_gap.column_gap, 0.0);
    }

    #[test]
    fn fragment_tree_retains_break_points_until_clear() {
        let mut tree = FragmentTree::default();
        let parent = tree.push(LayoutFragment {
            node_id: 1,
            parent: None,
            fragmentainer: 0,
            x: 0.0,
            y: 0.0,
            width: 40.0,
            height: 20.0,
            line_start: None,
            line_end: None,
        });
        assert_eq!(parent, 0);
        let nested = tree.push(LayoutFragment {
            node_id: 2,
            parent: None,
            fragmentainer: 0,
            x: 0.0,
            y: 0.0,
            width: 20.0,
            height: 10.0,
            line_start: None,
            line_end: None,
        });
        tree.reparent_roots(2, parent);
        assert_eq!(tree.fragments[nested].parent, Some(parent));
        tree.record_break(BreakToken {
            node_id: 1,
            child_index: 2,
            line_index: 0,
        });
        assert_eq!(tree.fragments.len(), 2);
        assert_eq!(tree.break_tokens.len(), 1);
        tree.clear();
        assert!(tree.fragments.is_empty());
        assert!(tree.break_tokens.is_empty());
    }
}
