[package]
name = "raikiri-feasibility"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
cssparser = { workspace = true }
selectors = { workspace = true }
taffy = { workspace = true }
parley = { workspace = true }
anyrender = { workspace = true }
peniko = { workspace = true }
kurbo = { workspace = true }
smol_str = { workspace = true }
rustc-hash = { workspace = true }
blitz-traits = { workspace = true }
blitz-paint = { workspace = true }
blitz-dom = { workspace = true }

[dev-dependencies]
anyrender_vello_cpu = { workspace = true }
tiny-skia = { workspace = true }
insta = { workspace = true }

[lints]
workspace = true
