//! Corpus entries of the text domain (`property/parse/text.rs`).

use super::{Entry, entry};

pub(super) const ENTRIES: &[Entry] = &[
    entry! {
        "font-style", font_style,
        parent: "italic",
        samples: ["normal", "italic", "oblique", "oblique 10deg", "slanted"],
    },
    entry! {
        "ruby-position", ruby_position,
        parent: "under",
        samples: ["over", "under", "alternate", "inter-character", "left"],
    },
    entry! {
        "font-family", font_family,
        parent: "\"Open Sans\", serif",
        samples: [
            "serif",
            "Arial, sans-serif",
            "\"Times New Roman\"",
            "Times New Roman, monospace",
            "system-ui",
            "1px",
            "Arial,",
        ],
    },
    entry! {
        "text-decoration-color", text_decoration_color,
        parent: "blue",
        samples: ["red", "currentcolor", "transparent", "#0f08", "bogus"],
    },
    entry! {
        "hyphenate-character", hyphenate_character,
        parent: "\"=\"",
        samples: ["auto", "\"-\"", "\"\"", "none", "abc"],
    },
    entry! {
        "hyphenate-limit-chars", hyphenate_limit_chars,
        parent: "5 2 2",
        samples: [
            "auto",
            "6",
            "6 3",
            "6 3 2",
            "auto 2",
            "6 auto 3",
            "-1",
            "2.5",
            "calc(2.4 + 1)",
        ],
    },
    entry! {
        "text-emphasis-color", text_emphasis_color,
        parent: "blue",
        samples: ["red", "currentcolor", "transparent", "bogus"],
    },
    entry! {
        "vertical-align", vertical_align,
        parent: "2em",
        lengths: "$",
        samples: [
            "baseline",
            "middle",
            "sub",
            "super",
            "text-top",
            "text-bottom",
            "top",
            "bottom",
            "-3px",
            "center",
        ],
    },
    entry! {
        "tab-size", tab_size,
        parent: "2em",
        lengths: "$",
        samples: ["8", "0", "4.5", "-1", "20px", "-1px"],
    },
    entry! {
        "text-decoration-thickness", text_decoration_thickness,
        parent: "2em",
        lengths: "$",
        samples: ["auto", "from-font", "3px", "-1px", "thick"],
    },
    entry! {
        "text-shadow", text_shadow,
        parent: "1px 2px 3px red",
        lengths: "$ 2px red",
        samples: [
            "none",
            "1px 2px",
            "red 1px 2px 3px",
            "1px 2px 3px blue, 4px 5px green",
            "1px 2px -3px",
            "1px",
            "1px 2px calc(1em + 2px) red",
        ],
    },
    entry! {
        "hanging-punctuation", hanging_punctuation,
        parent: "first",
        samples: [
            "none",
            "first last",
            "allow-end",
            "force-end first",
            "allow-end force-end",
            "bogus",
        ],
    },
    entry! {
        "direction", direction,
        parent: "rtl",
        samples: ["ltr", "rtl", "auto"],
    },
    entry! {
        "text-decoration-line", text_decoration_line,
        parent: "underline",
        samples: [
            "none",
            "underline overline",
            "line-through",
            "blink",
            "underline underline",
            "spelling-error",
            "grammar-error",
            "bogus",
        ],
    },
    entry! {
        "text-decoration-style", text_decoration_style,
        parent: "dashed",
        samples: ["solid", "double", "dotted", "wavy", "none"],
    },
    entry! {
        "text-transform", text_transform,
        parent: "uppercase",
        samples: [
            "none",
            "capitalize",
            "lowercase",
            "full-width",
            "full-size-kana",
            "uppercase full-width",
            "math-auto",
            "capitalize lowercase",
        ],
    },
    entry! {
        "word-break", word_break,
        parent: "break-all",
        samples: ["normal", "keep-all", "break-word", "auto-phrase", "manual"],
    },
    entry! {
        "overflow-wrap", overflow_wrap,
        parent: "anywhere",
        samples: ["normal", "break-word", "anywhere", "auto"],
    },
    entry! {
        "white-space", white_space,
        parent: "pre",
        samples: [
            "normal",
            "nowrap",
            "pre-wrap",
            "pre-line",
            "break-spaces",
            "collapse",
            "preserve nowrap",
            "bogus",
        ],
    },
    entry! {
        "white-space-collapse", white_space_collapse,
        parent: "preserve",
        samples: [
            "collapse",
            "preserve-breaks",
            "preserve-spaces",
            "break-spaces",
            "discard",
            "bogus",
        ],
    },
    entry! {
        "text-wrap-mode", text_wrap,
        parent: "nowrap",
        samples: ["wrap", "nowrap", "balance"],
    },
    entry! {
        "text-wrap-style", text_wrap_style,
        parent: "balance",
        samples: ["auto", "balance", "stable", "pretty", "avoid-orphans", "nowrap"],
    },
    entry! {
        "hyphens", hyphens,
        parent: "auto",
        samples: ["none", "manual", "auto", "all"],
    },
    entry! {
        "line-break", line_break,
        parent: "strict",
        samples: ["auto", "loose", "normal", "strict", "anywhere", "bogus"],
    },
    entry! {
        "text-justify", text_justify,
        parent: "inter-word",
        samples: [
            "auto",
            "none",
            "inter-word",
            "inter-character",
            "distribute",
            "bogus",
        ],
    },
    entry! {
        "text-align-last", text_align_last,
        parent: "center",
        samples: [
            "auto",
            "start",
            "end",
            "left",
            "right",
            "center",
            "justify",
            "match-parent",
            "bogus",
        ],
    },
    entry! {
        "text-combine-upright", text_combine_upright,
        parent: "all",
        samples: ["none", "all", "digits", "digits 2", "bogus"],
    },
    entry! {
        "text-orientation", text_orientation,
        parent: "upright",
        samples: ["mixed", "upright", "sideways", "sideways-right", "bogus"],
    },
    entry! {
        "unicode-bidi", unicode_bidi,
        parent: "isolate",
        samples: [
            "normal",
            "embed",
            "isolate",
            "bidi-override",
            "isolate-override",
            "plaintext",
            "bogus",
        ],
    },
    entry! {
        "font-variant-caps", font_variant_caps,
        parent: "small-caps",
        samples: [
            "normal",
            "small-caps",
            "all-small-caps",
            "petite-caps",
            "all-petite-caps",
            "unicase",
            "titling-caps",
            "bogus",
        ],
    },
    entry! {
        "text-decoration-skip-ink", text_decoration_skip_ink,
        parent: "none",
        samples: ["auto", "none", "all", "bogus"],
    },
    entry! {
        "text-decoration-skip-spaces", text_decoration_skip_spaces,
        parent: "none",
        samples: [
            "none",
            "all",
            "start",
            "end",
            "start end",
            "leading-spaces",
            "bogus",
        ],
    },
    entry! {
        "text-emphasis-position", text_emphasis_position,
        parent: "under left",
        samples: [
            "over",
            "under",
            "over right",
            "under left",
            "left over",
            "right",
            "bogus",
        ],
    },
    entry! {
        "text-underline-position", text_underline_position,
        parent: "under",
        samples: [
            "auto",
            "from-font",
            "under",
            "left",
            "right",
            "under left",
            "right from-font",
            "left right",
        ],
    },
    entry! {
        "text-underline-offset", text_underline_offset,
        parent: "2em",
        lengths: "$",
        samples: ["auto", "3px", "-2px", "0"],
    },
    entry! {
        "text-autospace", text_autospace,
        parent: "no-autospace",
        samples: [
            "normal",
            "auto",
            "no-autospace",
            "ideograph-alpha",
            "ideograph-numeric ideograph-alpha",
            "punctuation",
            "insert",
            "replace",
            "bogus",
        ],
    },
    entry! {
        "word-space-transform", word_space_transform,
        parent: "space",
        samples: [
            "none",
            "space",
            "ideographic-space",
            "auto-phrase",
            "space auto-phrase",
            "ideographic-space auto-phrase",
            "bogus",
        ],
    },
    entry! {
        "text-spacing-trim", text_spacing_trim,
        parent: "trim-start",
        samples: [
            "normal",
            "space-all",
            "space-first",
            "trim-start",
            "trim-both",
            "trim-all",
            "auto",
            "bogus",
        ],
    },
    entry! {
        "font-kerning", font_kerning,
        parent: "none",
        samples: ["auto", "normal", "none", "bogus"],
    },
    entry! {
        "font-optical-sizing", font_optical_sizing,
        parent: "none",
        samples: ["auto", "none", "bogus"],
    },
    entry! {
        "font-variant-emoji", font_variant_emoji,
        parent: "emoji",
        samples: ["normal", "text", "emoji", "unicode", "bogus"],
    },
    entry! {
        "font-variant-ligatures", font_variant_ligatures,
        parent: "none",
        samples: [
            "normal",
            "none",
            "common-ligatures",
            "no-common-ligatures discretionary-ligatures",
            "historical-ligatures contextual",
            "bogus",
        ],
    },
    entry! {
        "font-variant-position", font_variant_position,
        parent: "sub",
        samples: ["normal", "sub", "super", "bogus"],
    },
    entry! {
        "font-language-override", font_language_override,
        parent: "\"TRK\"",
        samples: ["normal", "\"SRB\"", "\"TOOLONG\"", "SRB"],
    },
    entry! {
        "font-synthesis", font_synthesis,
        parent: "none",
        samples: [
            "none",
            "weight",
            "style",
            "small-caps",
            "position",
            "weight style small-caps",
            "bogus",
        ],
    },
    entry! {
        "font-palette", font_palette,
        parent: "dark",
        samples: [
            "normal",
            "light",
            "dark",
            "--custom",
            "palette-mix(in lch, light, dark)",
            "bogus",
        ],
    },
    entry! {
        "font-variant-numeric", font_variant_numeric,
        parent: "tabular-nums",
        samples: [
            "normal",
            "lining-nums",
            "oldstyle-nums tabular-nums",
            "diagonal-fractions slashed-zero",
            "ordinal",
            "lining-nums oldstyle-nums",
        ],
    },
    entry! {
        "font-variant-east-asian", font_variant_east_asian,
        parent: "jis78",
        samples: [
            "normal",
            "jis78",
            "simplified full-width",
            "ruby",
            "proportional-width",
            "jis78 jis83",
        ],
    },
    entry! {
        "font-variation-settings", font_variation_settings,
        parent: "\"wght\" 700",
        samples: [
            "normal",
            "\"wght\" 700",
            "\"wght\" 700, \"wdth\" 50",
            "\"wdth\" 50, \"wght\" 700, \"wdth\" 60",
            "\"wgh\" 1",
            "wght 700",
        ],
    },
];
